### ISSUE TITLE
support elixir through asdf

### ISSUE THREAD

**Issue by petermm** [elixir-desktop/ios-example-app#1]
building couldn't find any elixir installed.. adding this to shell script (below the nvm line) makes it pick up asdf installed elixir/erlang
`[ -s "$HOME/.asdf/asdf.sh" ] && \. $HOME/.asdf/asdf.sh # This loads asdf`

**Comment by dominicletz** [comment]
https://github.com/elixir-desktop/ios-example-app/commit/bc87ef3997d5f0aa6de8b9d044c5a1391bbee375
