### ISSUE TITLE
/Users/zuzannakowal/projects/24.beta/activate: No such file or directory

### ISSUE THREAD

**Issue by tomekowal** [elixir-desktop/ios-example-app#3]
Hi! I've heard about the project in Thinking Elixir podcast.

I wanted to try it and when building I am getting the following error:

```
/Users/zuzannakowal/Library/Developer/Xcode/DerivedData/todoapp-brtxmrwciyidivgfgljugmuxqxyc/Build/Intermediates.noindex/todoapp.build/Debug-iphonesimulator/todoapp.build/Script-EC8A1FD6270B4EF900054F1C.sh: line 7: /Users/zuzannakowal/projects/24.beta/activate: No such file or directory
Command PhaseScriptExecution failed with a nonzero exit code
```

It might be an error with my setup. I am an elixir developer and just freshly installed xcode.

**Comment by amokan** [comment]
@tomekowal I may be mistaken, but looking at the README here https://github.com/elixir-desktop/ios-example-app#update-built-in-runtime it looks like that should setup that path for you

**Comment by tomekowal** [comment]
Oh, right. However, it does not work currently on Mac.
I get error described in this issue: https://github.com/erlang/otp/issues/5893
Am I correct that this command uses custom build without the patch mentioned in that issue?

**Comment by dominicletz** [comment]
Building this is still too difficult, but 25 is now out there and all external pieces are in place to make things easier. Will give a shot in the next couple of weeks.

**Comment by dominicletz** [comment]
Done, no need for the custom builds anymore!
